<?php

/**
 * @file
 */

/**
 * Implements hook_ajax_render_alter().
 */

use Drupal\views\ViewExecutable;

/**
 *
 */
function kwall_alert_system_ajax_render_alter(array &$data) {
  foreach ($data as $key => $command) {
    if ($command['command'] == 'viewsScrollTop') {
      unset($data[$key]);
      break;
    }
  }
}

/**
 *
 */
function kwall_alert_system_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'kwall_alert_system/dismissed-cookie';
}

/**
 *
 */
function kwall_alert_system_views_pre_render(ViewExecutable $view) {

  if ($view->id() == "alerts") {
    $dismissed = [];
    foreach ($view->result as $value) {
      $dismissed['key' . $value->_entity->get('nid')->value] = $value->_entity->get('nid')->value;
    }
    $view->element['#attached']['drupalSettings'] = [
      'kwall_alert_system' => ['dismissedCookie' => $dismissed],
    ];
  }
}
