<?php

/**
 * @file
 * This module extends link attributes.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements template_preprocess_field().
 */
function ala_preprocess_field(&$variables) {
  if ($variables['field_type'] == 'link') {
    $element = $variables['element'];
    foreach ($element['#items'] as $delta => $item) {
      if (!empty($element[$delta]['#options']['parent_classes'])) {
        $variables['items'][$delta]['attributes']->setAttribute('class', $element[$delta]['#options']['parent_classes']);
      }
    }
  }
}

/**
 * Implements hook_help().
 */
function ala_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ala':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
