<?php

/**
 * @file
 *
 *
 *
 * @author Attila Fekete - http://drupal.org/user/762986
 */

define('SOUNDCLOUDFIELD_DEFAULT_WIDTH', 100);
define('SOUNDCLOUDFIELD_DEFAULT_HTML5_PLAYER_HEIGHT', 166);
define('SOUNDCLOUDFIELD_DEFAULT_HTML5_PLAYER_HEIGHT_SETS', 450);
// Usable sizes for visual player: 300, 450, 600.
define('SOUNDCLOUDFIELD_DEFAULT_VISUAL_PLAYER_HEIGHT', 450);

/**
 * Curl helper function.
 */
function _soundcloudfield_curl_get($url) {
  $client = \Drupal::httpClient();
  try {
    $request = $client->get($url);
    return $request->getBody()->getContents();
  }
  catch (\Exception $e) {
    \Drupal::logger('soundcloudfield')->error($e->getMessage());
  }
  return FALSE;
}
